function procCmd(cmd){
function newLevel(){
function destroyBlock(x,y,z,side){
function createWood(x,y,z,bi,bd,c){
function addWood(x,y,z,i,d,c,l){
function useItem(x,y,z,itemId,blockId,side,itemData,blockData){
function projectileHitBlockHook(entity,x,y,z,side){
function umeru(x,y,z,id,dm){
function addLine(x,y,z,mx,my,mz,nx,ny,nz,blockId,blockData){
function addLine2(x,y,z,mx,my,mz,nx,ny,nz,blockId,blockData,lb){
function addLeaves(x,y,z,i,d){
function getRot(x1,z1,x2,z2){
function addBBP(nx,ny,nz,px,py,pz,id,data){
